# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vets_cpp_llh_equicor <- function(model, Amat, Fmat, Hmat, Gmat, States, Y, X, beta) {
    .Call(`_tsvets_vets_cpp_llh_equicor`, model, Amat, Fmat, Hmat, Gmat, States, Y, X, beta)
}

vets_cpp_llh_diagonal <- function(model, Amat, Fmat, Hmat, Gmat, States, Y, X, beta) {
    .Call(`_tsvets_vets_cpp_llh_diagonal`, model, Amat, Fmat, Hmat, Gmat, States, Y, X, beta)
}

vets_cpp_llh_full <- function(model, Amat, Fmat, Hmat, Gmat, States, Y, X, beta) {
    .Call(`_tsvets_vets_cpp_llh_full`, model, Amat, Fmat, Hmat, Gmat, States, Y, X, beta)
}

vets_cpp_llh_shrink <- function(model, Amat, Fmat, Hmat, Gmat, States, Y, X, beta) {
    .Call(`_tsvets_vets_cpp_llh_shrink`, model, Amat, Fmat, Hmat, Gmat, States, Y, X, beta)
}

vets_cpp_filter <- function(model, Amat, Fmat, Hmat, Gmat, States, Y, X, beta) {
    .Call(`_tsvets_vets_cpp_filter`, model, Amat, Fmat, Hmat, Gmat, States, Y, X, beta)
}

vets_cpp_predict <- function(model, S, Amat, Fmat, Hmat, Gmat, istate, X, beta) {
    .Call(`_tsvets_vets_cpp_predict`, model, S, Amat, Fmat, Hmat, Gmat, istate, X, beta)
}

vets_cpp_simulate <- function(model, E, Amat, Fmat, Hmat, Gmat, istate, X, beta) {
    .Call(`_tsvets_vets_cpp_simulate`, model, E, Amat, Fmat, Hmat, Gmat, istate, X, beta)
}

